### PR TITLE
New field for invoices

### PR DESCRIPTION
**Pull request by hertell**
Lisäsin viitteemme-kentän, sillä tämä on usein käytössä laskuissa (esim myyjän nimi). Muistin että myös finvoice-tiedosto tulisi päivittää, joten teen tämän seuraavaksi. (ourreference->SellerReferenceIdentifier)

Edit. Looks that the finvoice-patch got also included into the pull-request.. I'm not a master of git or github, so sorry if theis is not working out correctly

### CODE REVIEW

**Comment by emaijala** [comment]
Thanks! I'll keep this in English for any international audience. :) 

I'd appreciate if you could fix a couple of minor issues before I can merge this:

1.) ourreference => our_reference in the database to keep the naming consistent (as far as possible)
2.) Translations also to Swedish and English language files (fi-FI.ini, en-US.ini)
3.) Typo in the Finnish translation, "Viiteemme"
4.) Database upgrade scripts remain only for conversion from legacy versions. These days all the database changes are done automatically in sqlfuncs.php verifyDatabase function. You should check the database version, make the changes and update the version. 
5.) Database version must be updated also in create_database.sql. See the line:

        INSERT INTO mlinvoice_state (id, data) VALUES ('version', '37');

**Comment by emaijala** [comment]
@hertell, will you be able to address the comments?

**Comment by hertell** [comment]
@emaijala i got this fixed, but i'm a mess with git, so i have to see how i manage to get a new pull-request with your recet updates merged into my fork.....

**Comment by emaijala** [comment]
I'm closing this pull request for now. Please open a new one when things are sorted out. Thanks!

**Pull request closed without merging**
