### PR TITLE
Mailgun support

### PR DESCRIPTION
**Pull request by mongrelx**
in config.php 
'send_method' => 'mailgun'
'mailgun' =>  [
'key' => 'xxxx',
'domain => 'yyyy.zz'
]

### CODE REVIEW

**Comment by emaijala** [comment]
Thanks for this! A couple of suggestions/requests:

1. I think it would be more clear if you'd add a new method that handles Mailgun (e.g. sendWithMailgun). Then check the send method in the very beginning of sendEmail() and call sendWithMailgun right away.
2. Since you only use the Mailgun class once, there's no real need for the use clause. Just use `new \Mailgun\Mailgun(..)`
3. I don't know Mailgun requirements, but is the currently used Guzzle not suitable? How about if it's updated so that we don't need two different ones?
4. I think it would be clearest to always include Mailgun in composer.json instead of just suggest. Since many use automatic installs from packages, requiring composer to use Mailgun would be too complicated. I can of course make the package creation add Mailgun too if there are downsides to always including it.
5. Please make Travis happy!

**Comment by mongrelx** [comment]
guzzlehttp/psr7 is PSR-7 Message Implementation not another version.
I have no idea why travis is failing

**Comment by emaijala** [comment]
Couple more issues I noticed:

1. sendMessage() is deprecated, so it should not be used in new code anymore.
2. Indentation has been lost in many places with the ternary operator (?:).
3. Add sample settings to config.php.sample.
4. Always use short array syntax [] instead of array().

Thanks!

**Comment by emaijala** [comment]
Superseded by #388. With that, you can use Mailgun by using one of the following settings for 'dsn' in config.php:

- `mailgun+smtp://USERNAME:PASSWORD@default`
- `mailgun+https://KEY:DOMAIN@default`
- `mailgun+api://KEY:DOMAIN@default`

**Pull request closed without merging**
