### PR TITLE
Added setting to display terms text in dispatch notes

### PR DESCRIPTION
**Pull request by rulex**
* Added setting for dispatch notes to also show client name in right side column above client id
* and a small swedish lang fix

note again the finnish translations :smile_cat:

### CODE REVIEW

**Comment by emaijala** [comment]
Perhaps dispatch note terms should be in the base table so that it can be defined per invoicing company? Is there a relation to the terms of delivery that can be modified at the invoice level but has client-specific defaults?

**Comment by rulex** [comment]
Here's a terms example for what we are using it: `Mahdollinen reklamaatio tulee ilmoittaa lähettäjälle viimeistään 24 tuntia tavaran vastaanottamisesta`

Yes, didn't think of that since we are using only one invoicing company, but that would probably be better to be able to define per invoicing company...

We are not using any of the delivery stuff either at the moment.

**Comment by emaijala** [comment]
Would you be able to work on adding the default to the invoicing company or would you rather let me handle that?

**Comment by rulex** [comment]
It's probably better if you take care of that :smirk_cat:

**Comment by emaijala** [comment]
Ok, will do as soon as I can get to it. I'll leave this pull request open until it's done.

**Comment by emaijala** [comment]
I couldn't quite decide yet if there's a good way to integrate the text field without adding something that's quite specific to dispatch notes. Do you think the recently added support for foreword before the actual "invoice" lines could be used for the text instead? There is a default for it in the invoicing company and as of today there's also the possibility to quickly pick a predefined text from settings.

The translation fix has been incorporated but I also got stuck with the client name in the right column. What's the use case? It feels a bit superfluous since it's already in the left column.

**Comment by emaijala** [comment]
Closing for now. Please reopen if necessary.

**Pull request closed without merging**
